---
- hosts: stellar
  sudo: true
  vars:
  tasks:
#  - name: Install prerequisites
#    apt:
#      name: "{{item}}"
#      state: present
#    loop:
#      - dnsutils
#      - apt-transport-https
#      - vim
#      - pv
#      - haproxy
#      - less
#      - netcat
#      - curl
#      - supervisor
#  - name: Download and install the public signing key
#    shell: wget -qO - https://apt.stellar.org/SDF.asc | apt-key add -
#  - name: Save the repository definition to /etc/apt/sources.list.d/SDF.list
#    shell: echo "deb https://apt.stellar.org/public stable/" | tee -a /etc/apt/sources.list.d/SDF.list
#  - name: Install Quickstart
#    shell: apt update && apt-get install stellar-quickstart -y
#    ignore_errors: yes
#  - name: Migrate Horizon DB
#    shell: . /etc/default/stellar-horizon  /etc/default/stellar-horizon db migrate up
  - name: Copy utils
    copy:
      src: utils/
      dest: /usr/local/bin/
      mode: a=x
  - name: Configure services
    template:
      src: supervisor-service.conf.j2
      dest: "/etc/supervisor/conf.d/{{item.name}}.conf"
    vars:
      name: "{{item.name}}"
      command: "{{item.command}}"
    loop:
      - {name: 'healthz', command: '/usr/local/bin/healthz.sh'}
      - {name: 'stellar-core-lag-monitor', command: '/usr/local/bin/stellar-core-lag-monitor.sh'}
      - {name: 'stellar-horizon-lag-monitor', command: '/usr/local/bin/stellar-horizon-lag-monitor.sh'}
  - supervisorctl:
      name: "{{item.name}}"
      state: restarted
      config: /etc/supervisor/supervisord.conf
    loop:
      - {name: 'healthz', command: '/usr/local/bin/healthz.sh'}
      - {name: 'stellar-core-lag-monitor', command: '/usr/local/bin/stellar-core-lag-monitor.sh'}
      - {name: 'stellar-horizon-lag-monitor', command: '/usr/local/bin/stellar-horizon-lag-monitor.sh'}


